### ISSUE TITLE
Support the light and dark theme

### ISSUE THREAD

**Issue by hbcarlos** [QuantStack/jupyterlab-blockly#5]
Since we have two themes available in JupyterLab (light and dark) would be great to support themes in blockly, so when changing to the dark theme, the blockly editor changes to follow the same design.

Some documentation to get started:
* [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/developer/css.html)
* [Blockly](https://developers.google.com/blockly/guides/configure/web/themes)

**Comment by hbcarlos** [comment]
### This is an example of how to track JupyterLab theme changes

We need to import the token `IThemeManager` from the package `@jupyterlab/apputils`, and the interface `IChangedArgs` from the package `@jupyterlab/coreutils`. Then we need to require the token `IThemeManager` in our plugin here:
https://github.com/QuantStack/jupyterlab-blockly/blob/3e326e2e61b677ef4a9122052459d14189501159/src/index.ts#L21-L25

```typescript
const plugin: JupyterFrontEndPlugin<void> = {
  id: 'jupyterlab-blocky:plugin',
  autoStart: true,
  requires: [ILayoutRestorer, IThemeManager],
  activate: (app: JupyterFrontEnd, restorer: ILayoutRestorer, themeManager: IThemeManager) => {...}
```

Once required in our plugin, we can track changes on the theme by doing the following:
```typescript
manager.themeChanged.connect((sender: IThemeManager, args: IChangedArgs<string, string | null, string>) => {
      // Obtain the name of the active theme from 'sender' or 'args'

      // Logic to change the theme in Blockly
});
```

We can access the `args.newValue` object to check the name of the new theme. Probably (but not sure), `JupyterLab Light` or `JupyterLab Dark` for the default themes.
Another way could be checking the name of the active theme in the object `sender.theme`.

**Comment by DenisaCG** [comment]
In order to change the Blockly theme in accordance with the JupyterLab one, I made two functions: one for changing the Blockly theme every time the JupyterLab theme changes, and one which injects Blockly with the proper theme (without it Blockly would open with a light theme even when JupyterLab had a dark theme, and vice versa -- not sure if there is an easier way to avoid this) :  
https://github.com/DenisaCG/jupyterlab-blockly/blob/7b7183c494125c8615ad5aee0902392124714a7f/src/layout.ts#L147-L183
 
I also defined a [dark theme](https://github.com/google/blockly-samples/blob/aba88bea60bddf3d31ce630b836e2933836ed287/plugins/theme-dark/src/index.js) for Blockly and declared it in the utils.ts file : https://github.com/DenisaCG/jupyterlab-blockly/blob/7b7183c494125c8615ad5aee0902392124714a7f/src/utils.ts#L367-L384
