### ISSUE TITLE
Blocky language

### ISSUE THREAD

**Issue by adeayopy** [QuantStack/jupyterlab-blockly#81]
Hi,
I installed blockly using 'development install' but the toolkit is not in english language. How do I change that?
Thanks

**Comment by DenisaCG** [comment]
Hey @adeayopy. Sorry for the delayed response! 

The toolbox should automatically adapt to the language you are using in JupyterLab. Once you switch the language in JupyterLab to English, it should also switch the language for the blocks inside the toolbox to English.

The development install also includes two other language packages (Spanish and French), only for testing purposes of the internationalization. Maybe JupyterLab is automatically switching to one of those languages, but going back to English should still be possible.

If this doesn't fix your issue, please give me more information - such as what language is JupyterLab in? and is it different than the one for the toolbox?

**Comment by DenisaCG** [comment]
There seems to be an issue which makes `jupyterlab-blockly` activate in Lithuanian. I will investigate it further. For now, you can try switching to another language in JupyterLab, such as Spanish, and then back to English and your toolbox should appear in the chosen language. 

Thank you for opening this issue!

**Comment by DenisaCG** [comment]
The issue seems to be related with the version of `JupyterLab` that is being using, as the extension is not yet compatible with `v4`. As long as during the development installation process, the proper version is used, the errors should not appear. 

You can do this by following the [development install instructions](https://github.com/QuantStack/jupyterlab-blockly?tab=readme-ov-file#development-install) which creates an enviroment with `v.3.6` of `JupyterLab`.
